# Generated by Django 5.0.1 on 2024-02-15 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('dbid', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('book_name', models.CharField(max_length=100)),
                ('ISBN', models.CharField(default='', max_length=50)),
                ('pub_time', models.DateField()),
                ('price', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ManyToManyField(blank=True, related_name='books', to='authors.author')),
                ('categories', models.ManyToManyField(related_name='books', to='categories.category')),
                ('publisher', models.ManyToManyField(blank=True, related_name='books', to='publishers.publisher')),
            ],
        ),
    ]
